# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=140)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=140)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('psw', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='posted_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_posted', to='wall.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_comments', to='wall.Message'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_posted', to='wall.User'),
        ),
    ]
