# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20170921_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fname',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lname',
            field=models.CharField(max_length=20, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='psw',
            field=models.CharField(max_length=20, verbose_name='password'),
        ),
    ]
